config/routes.rb
Rails.application.routes.draw do
  
  get 'customers', to: 'customers#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :account, only: [:show, :edit, :update]

  resources :casefiles do
    post :import, on: :collection
    get :get_report, on: :collection
  end
  resources :projects do 
    resources :costs
  end
  resources :rehouses
  resources :landfs
  resources :inherits
  resources :genes
  resources :commons
  resources :corps
  resources :newbuilds
  resources :mitsuwa_docs
  resources :mistakes
  resources :judges

  resources :estates, only: :index
  resources :lands do
    post :import, on: :collection
  end
  resources :buildings do
    post :import, on: :collection
  end
  resources :aparts do
    post :import, on: :collection
  end
  resources :rooms do
    post :import, on: :collection
  end

  resources :gifts
  resources :addresses
  resources :tels
  resources :mails
  resources :costs
  resources :customer_agents
  resources :branch_staffs
  resources :identifies
  resources :branches do
    resources :branch_staffs
  end

  resources :controls do
    resources :addresses do
      get :addaddr, on: :collection
    end
    resource :tels do
      get :addcontrol, on: :collection
    end
    resources :mails do
      get :addcontrol, on: :collection
    end
    post :import, on: :collection
  end

  resources :people do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    post :import, on: :collection
  end

  resources :companies do
    resources :addresses
    resources :identifies
    resources :branches
    resources :tels
    resources :mails
    post :import, on: :collection
  end

  resources :agents do
    resources :addresses
  end

  resources :customers do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    resources :gifts
    resources :customer_agents
  end

  namespace :admin do
    resources :users
  end

  # ---------------------------------
  # 仮のルートページ
  # ---------------------------------
  root 'customers#index'
end

app/models/control.rb
class Control < ApplicationRecord
  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses
  has_many :tels, as: :telable, dependent: :destroy
  accepts_nested_attributes_for :tels
  has_many :mails, as: :mailable, dependent: :destroy
  accepts_nested_attributes_for :mails
  has_many :lands
  has_many :buildings
  has_many :rooms
  has_many :company_controls, foreign_key: :control_id, dependent: :destroy
  has_many :companies, through: :company_controls, source: :company
  accepts_nested_attributes_for :company_controls, allow_destroy: true
  has_many :judges, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w(name)
  end

  def self.ransackable_associations(_auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s }
  end

  def self.csv_attributes
    %w(id number name remark created_at updated_at)
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |control|
        csv << csv_attributes.map { |attr| control.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      control = new
      control.attributes = row.to_hash.slice(*csv_attributes)
      control.save!
    end
  end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  before_action :set_control, only: [:show, :edit, :update, :destroy
  ]
  def index
    @q = Control.ransack(params[:q])
    @controls = @q.result.order('controls.created_at asc').page(params[:page]).per(10)
    @ex_controls = @q.result(distinct: true)

    respond_to do |format|
      format.html
      format.csv { send_data @ex_controls.generate_csv, filename: "control-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def show
  end

  def new
    @control = Control.new
    @control.addresses.build
  end

  def edit
  end

  def create
    @control = Control.new(control_params)
    @control.addresses.build(address_params)

    if @control.save
      redirect_to control_path(@control), notice: "#{@control.name}を登録しました。"
    else
      render :new
    end
  end

  def update
    if @control.update(control_params)
      redirect_to control_path(@control), notice: "#{@control.name}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @control.destroy
    redirect_to controls_path, notice: "#{@control.name}を削除しました。"
  end

  def import
    Control.import(params[:file])
    redirect_to controls_path, notice: "登記所をファイルから追加しました。"
  end

  def control_params
    params.require(:control).permit(:number, :name, :remark, tels_attributes: [:id, :tel_kind, :tel_number, :_destroy], mails_attributes: [:id, :mail_kind, :mail_address, :_destroy])
  end

  def address_params
    params.require(:address).permit(:zip, :address, :since_date, :address_kind, :address_closure)
  end

  def set_control
    @control = Control.find(params[:id])
  end
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_edit_form.html.slim
- if control.errors.present?
  ul#error_explanation
    - control.errors.full_messages.each do |message|
      li = message
= form_with model: control, local: true do |f|
  .form-group
    = f.label :number, '登記所ID'
    = f.text_field :number, class: 'form-control'
  .form-group
    = f.label :name, '登記所名'
    = f.text_field :name, class: 'form-control'
  #tels.mb-2
    = f.fields_for :tels do |tel|
      = render 'tel_fields', f: tel
    .links
      = link_to_add_association '電話番号追加', f, :tels, class: 'btn btn-primary'
  #mails.mb-2
    = f.fields_for :mails do |tel|
      = render 'mail_fields', f: tel
    .links
      = link_to_add_association 'メールアドレス追加', f, :mails, class: 'btn btn-primary'
  .form-group
    = f.label :remark, '備考'
    = f.text_area :remark, rows: 10, placeholder: "登記識別情報開始日等",class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary mt-3 mb-3	'


app/views/controls/_form.html.slim
- if control.errors.present?
  ul#error_explanation
    - control.errors.full_messages.each do |message|
      li = message
= form_with model: control, local: true do |f|
  .form-group
    = f.label :number, '登記所ID'
    = f.text_field :number, class: 'form-control'
  .form-group
    = f.label :name, '登記所名'
    = f.text_field :name, class: 'form-control'
  .form-group
    = fields_for :address do |addr|
      = addr.label :zip, '郵便番号'
      = addr.text_field :zip, class: 'form-control'
      = addr.label :address, '住所'
      = addr.text_field :address, class: 'form-control'
      = addr.label :since_date, '住定日'
      = addr.date_field :since_date, class: 'form-control'
      = addr.label :address_kind, '住所の種類'
      = addr.text_field :address_kind, class: 'form-control'
      = addr.hidden_field :address_closure, value: false, class: 'form-control'
  #tels.mb-2
    = f.fields_for :tels do |tel|
      = render 'tel_fields', f: tel
    .links
      = link_to_add_association '電話番号追加', f, :tels, class: 'btn btn-primary'
  #mails.mb-2
    = f.fields_for :mails do |tel|
      = render 'mail_fields', f: tel
    .links
      = link_to_add_association 'メールアドレス追加', f, :mails, class: 'btn btn-primary'
  .form-group
    = f.label :remark, '備考'
    = f.text_area :remark, rows: 10, placeholder: "登記識別情報開始日等",class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary mt-3 mb-3	'


app/views/controls/_mail_fields.html.slim
.nested-fields.well.well-compact
  .form-group
    = f.hidden_field :id
    .row
      .col-sm-3
        = f.label :mail_kind, 'メール種類'
        = f.text_field :mail_kind, class: 'form-control'
      .col-sm-6
        = f.label :mail_address, 'メールアドレス'
        = f.text_field :mail_address, class:  'form-control'
      .col-sm-3
        = link_to_remove_association '削除', f, class: 'btn btn-danger mt-4'

app/views/controls/_tel_fields.html.slim
.nested-fields.well.well-compact
  .form-group
    = f.hidden_field :id
    .row
      .col-sm-3
        = f.label :tel_kind, '電話種類'
        = f.text_field :tel_kind, class: 'form-control'
      .col-sm-6
        = f.label :tel_number, '電話番号'
        = f.text_field :tel_number, class:  'form-control'
      .col-sm-3
        = link_to_remove_association '削除', f, class: 'btn btn-danger mt-4'

app/views/controls/edit.html.slim
- @page_title = '登記所編集'
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '登記所詳細へ', control_path, class: 'nav-link btn btn-primary'
  = link_to '登記所一覧へ', controls_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'

= render 'edit_form', control: @control

app/views/controls/index.html.slim
- @page_title = "登記所"
h3.mb-3.mt-3 = @page_title

nav.navbar.navbar-expand-md.navbar-dark.bg-primary 
  ul.navbar-nav.mr-auto
    li.nav-item = link_to '登記所新規作成', new_control_path, class: 'nav-link text-white'
    li.nav-item = link_to '案件一覧', projects_path, class: 'nav-link text-white'
    li.nav-item = link_to '事件簿', casefiles_path, class: 'nav-link text-white'
    li.nav-item = link_to '不動産一覧', estates_path, class: 'nav-link text-white'
button#search-btn.btn-warning.m-2.d-print-none= "検索表示"
fieldset#search.border.mb-3.d-none
  legend.pl-3 検索
  .pl-1
    = search_form_for @q, class: 'mb-5' do |f|
      .from-group.row.mb-4
        .col-sm-2.text-right
          = f.label :name_cont, '登記所名', class: ' col-form-label mt-2'
        .col-sm-9
          = f.search_field :name_cont, class: 'form-control mt-2'
      .form-group.row.mb-4
        .col-sm-2.text-right
          = f.label :tels_tel_number_cont, '電話番号', class: ' col-form-label mt-2'
        .col-sm-9
          = f.search_field :tels_tel_number_cont, class: 'form-control mt-2'
        .form-group
          = f.submit class: 'btn btn-outline-primary mt-2 ml-2' 


.mb-3
  = paginate @controls
  = page_entries_info @controls

.mb-3
table.table.table-hover.table-bordered.text-center
  thead.table-default
    tr
      th = Control.human_attribute_name(:id).upcase
      th = sort_link(@q, :number)
      th = Control.human_attribute_name(:name)
      th = Control.human_attribute_name(:created_at)
      th = Control.human_attribute_name(:updated_at)
      th
  tbody
    - @controls.each do | control |
      tr
        td = control.id
        td = control.number
        td = link_to control.name, control_path(control)
        td = control.created_at.try(:strftime,'%Y/%m/%d')
        td = control.updated_at.try(:strftime,'%Y/%m/%d')
        td 
          = link_to '編集', edit_control_path(control), class: 'btn btn-primary mr-3'
          -if current_user.admin?
            = link_to '削除', control, method: :delete, data: { confirm: "#{control.name}を削除します。よろしいですか？" }, class: 'btn btn-danger'

= link_to 'エクスポート', controls_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_controls_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag 'インポート', class: 'btn btn-primary'

app/views/controls/new.html.slim
- @page_title = "登記所新規作成"
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '登記所一覧へ', controls_path, class: 'nav-link btn btn-primary'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'

= render 'form', control: @control

app/views/controls/show.html.slim
- @page_title = "登記所詳細"
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '編集', edit_control_path, class: 'btn btn-primary mb-3'
  - if current_user.admin?
    = link_to '削除', :control, method: :delete, data: {confirm: "#{@control.name}を削除してよろしいですか？" }, class: 'btn btn-danger mb-3 ml-3'
  = link_to '住所追加', addaddr_control_addresses_path(@control), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '電話追加', addcontrol_control_tels_path(@control), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to 'メール追加', addcontrol_control_mails_path(@control) , class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '登記所一覧', controls_path, class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '不動産一覧', "#", class: 'nav-link btn btn-primary mb-3 ml-3'

table.table.table-hover.table-bordered
  tbody
    tr
      th.w-25 = Control.human_attribute_name(:id).upcase
      td = @control.id
    tr
      th = Control.human_attribute_name(:number)
      td = @control.number
    tr
      th = Control.human_attribute_name(:name)
      td = @control.name  
    tr
      th = Control.human_attribute_name(:address)
      td
        - if @control.addresses.present?
          - @control.addresses.order('since_date desc').each do |a|
            - if a.address_closure == false
              card.row              
                .col-sm-4
                  = "住定日(or確認日):  #{a.since_date.try(:strftime,'%Y/%m/%d')}"
                .col-sm-5
                  |　住所の種類：
                  = a.address_kind
              .row.mb-2
                .col-sm-2
                  = "〒#{a.zip}"
                .col-sm-7
                  = a.address
                .col-sm-1
                  = link_to "編集", [:edit, @control, a], class: 'btn btn-primary pull-right'
                .col-sm-1
                  = link_to "削除", [@control, a], method: :delete, data: {confirm: "#{a.address}を削除します。よろしいですか？"} ,class: 'btn btn-danger pull-right'
    tr
      th = Control.human_attribute_name(:tel)
      td
        - @control.tels.each do |tel|
          .row.mb-2
            .col-sm-3
              = tel.tel_kind
            .col-sm-3
              = tel.tel_number
    tr
      th = Control.human_attribute_name(:mail)
      td
        - @control.mails.each do |mail|
          .row.mb-2
            .col-sm-3
              = mail.mail_kind
            .col-sm-3
              = mail_to mail.mail_address
    tr
      th = Control.human_attribute_name(:remark)
      td = simple_format(@control.remark)
    tr
      th = Control.human_attribute_name(:created_at)
      td = @control.created_at.try(:strftime,'%Y/%m/%d')
    tr
      th = Control.human_attribute_name(:updated_at)
      td = @control.updated_at.try(:strftime,'%Y/%m/%d')