config/routes.rb
Rails.application.routes.draw do
  
  get 'customers', to: 'customers#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :account, only: [:show, :edit, :update]

  resources :casefiles do
    post :import, on: :collection
    get :get_report, on: :collection
  end
  resources :projects do 
    resources :costs
  end
  resources :rehouses
  resources :landfs
  resources :inherits
  resources :genes
  resources :commons
  resources :corps
  resources :newbuilds
  resources :mitsuwa_docs
  resources :mistakes
  resources :judges

  resources :estates, only: :index
  resources :lands do
    post :import, on: :collection
  end
  resources :buildings do
    post :import, on: :collection
  end
  resources :aparts do
    post :import, on: :collection
  end
  resources :rooms do
    post :import, on: :collection
  end

  resources :gifts
  resources :addresses
  resources :tels
  resources :mails
  resources :costs
  resources :customer_agents
  resources :branch_staffs
  resources :identifies
  resources :branches do
    resources :branch_staffs
  end

  resources :controls do
    resources :addresses do
      get :addaddr, on: :collection
    end
    resource :tels do
      get :addcontrol, on: :collection
    end
    resources :mails do
      get :addcontrol, on: :collection
    end
    post :import, on: :collection
  end

  resources :people do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    post :import, on: :collection
  end

  resources :companies do
    resources :addresses
    resources :identifies
    resources :branches
    resources :tels
    resources :mails
    post :import, on: :collection
  end

  resources :agents do
    resources :addresses
  end

  resources :customers do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    resources :gifts
    resources :customer_agents
  end

  namespace :admin do
    resources :users
  end

  # ---------------------------------
  # 仮のルートページ
  # ---------------------------------
  root 'customers#index'
end

app/models/newbuild.rb
class Newbuild < Project
  has_many :casefiles, foreign_key: :project_id, dependent: :destroy
  has_many_attached :images
  has_many :project_customers, foreign_key: :project_id, inverse_of: :project, dependent: :destroy
  has_many :customers, through: :project_customers
  accepts_nested_attributes_for :project_customers,  reject_if: :all_blank, allow_destroy: true
  has_many :project_estates, foreign_key: :project_id, inverse_of: :project, dependent: :destroy
  has_many :estates, through: :project_estates
  accepts_nested_attributes_for :project_estates,  reject_if: :all_blank, allow_destroy: true

  has_many :certificates, foreign_key: :project_id, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :certificates, allow_destroy: true
  has_many :destinates, foreign_key: :project_id, dependent: :destroy
  accepts_nested_attributes_for :destinates, allow_destroy: true
  has_many :costs, foreign_key: :project_id, dependent: :destroy
  accepts_nested_attributes_for :costs
  has_many :judges, foreign_key: :project_id, dependent: :destroy
  belongs_to :user
end

app/controllers/newbuilds_controller.rb
class NewbuildsController < ApplicationController
  before_action :set_newbuild, only: [:show, :edit, :update, :destroy]

  def index
    @q = Newbuild.ransack(params[:q])
    @newbuilds = @q.result.order('projects.created_at desc').page(params[:page]).per(10)
  end

  def show
  end

  def new
    @newbuild = Newbuild.new
    @newbuild.project_estates.build
    @newbuild.project_customers.build
  end

  def edit
  end

  def create
    @newbuild = Newbuild.new(newbuild_params)

    if @newbuild.save
      redirect_to newbuild_path(@newbuild), notice: "#{@newbuild.name}を登録しました。"
    else
      render :new
    end
  end

  def update
    if params[:newbuild][:image_ids].present?
      params[:newbuild][:image_ids].each do |image_id|
        image = @newbuild.images.find(image_id)
        image.purge
      end
    end
    if @newbuild.update(newbuild_params)
      redirect_to newbuild_path(@newbuild), notice: "#{@newbuild.name}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @newbuild.destroy
    redirect_to newbuilds_path, notice: "#{@newbuild.name}を削除しました。"
  end

  private

  def newbuild_params
    params.require(:newbuild).permit(:type, :name, :status, :application_date, :complete_date, :user_id, :request_content, :remarks, :images, project_customers_attributes: [:id, :customer_id, :project_id, :position, :equity, :_destroy], project_estates_attributes: [:id, :project_id, :estate_id, :_destroy], certificates_attributes: [:id, :project_id, :cert_kind, :number_sheet, :window, :_destroy], destinates_attributes: [:id, :project_id, :customer_id, :send_method, :send_addr, :send_date, :send_number, :receive_doc, :_destroy])
  end

  def project_customer_params
    params.require(:project_customers).permit(:customer_id, :project_id, :position, :equity)
  end

  def set_newbuild
    @newbuild = Newbuild.includes({ project_customers: [:customer] }, { project_estates: [estate: [:control]] }, { destinates: [:customer] }).find(params[:id])
  end
end

app/helpers/newbuilds_helper.rb
module NewbuildsHelper
end

app/views/newbuilds/_certificate_fields.html.slim
.nested-fields.well.well-compact.mb-4
  .form-group.mb-2
    = f.hidden_field :id 
  .form-group.mb-2
    = f.label :cert_kind, '謄本等種類'
    = f.select :cert_kind, ["土地", "建物", "商業", "印鑑証明", "その他"], {include_blank: true, prompt: "選択してください"}, class: 'form-control select2'
  .form-group.mb-2
    = f.label :number_sheet, "謄本等通数"
    = f.number_field :number_sheet, class: 'form-control'
  .form-group.mb-2
    = f.label :window, "窓口受領"
    = f.check_box :window, class: 'form-check-input m-2'
  .form-group.mb-2
    = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/newbuilds/_destinate_fields.html.slim
.nested-fields.well.well-compact.mb-4
  .form-group.mb-4
    = f.hidden_field :id 
  .form-group.mb-2
    = f.label :customer_id, '顧客氏名'
    = f.collection_select(:customer_id, f.object.selectable_customers, :id, :view_name_select, {include_blank: true, prompt: "選択してください"}, class: 'form-control select2')
  .form-group.mb-2
    = f.label :send_method, '手渡'
    = f.check_box :send_method, class: 'form-check-input m-2'
  .form-group.mb-2
    = f.label :send_addr, '送付先／手渡先'
    = f.text_field :send_addr, class: 'form-control'
  .form-group.mb-2
    = f.label :send_date, '送付／手渡日'
    = f.date_field :send_date, class: 'form-control'
  .form-group.mb-2
    = f.label :send_number, '書留等番号'
    = f.text_field :send_number, class: 'form-control'
  .form-group.mb-2
    = f.label :receive_doc, '受領書返送'
    = f.check_box :receive_doc, class: 'form-check-input m-2'
  .form-group.mb-2
    = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/newbuilds/_form.html.slim
- if newbuild.errors.present?
  ul#error_explanation
    - newbuild.errors.full_messages.each do |message|
      li = message
= form_with model: newbuild, local: true do |f|
  .form-group
    = f.label :name, '案件名'
    = f.text_field :name, class: 'form-control'

  .form-group.row
    .col-sm-10
      = f.label :status, '進捗状況'
      = f.text_field :status, class: 'form-control'
    .col-sm-2
      = f.label :user_id, '事務所担当者'
      = f.collection_select(:user_id, User.all, :id, :name, {prompt: true, selected: current_user.id}, {class: 'form-control'})

  .form-group
    = f.label :request_content, '依頼内容等'
    = f.text_area :request_content, row: 10, class: 'form-control'

  #project_estates.mb-4.mt-4
    = f.fields_for :project_estates do |project_estate|
      = render 'project_estate_fields', f: project_estate
    .links
      = link_to_add_association '不動産追加', f, :project_estates, class: 'btn btn-primary'
    .estate-link.mt-4.mb-4
      = link_to '不動産一覧へ', estates_path, target: "_blank", class: 'btn btn-primary'

  #project_customers.mb-4.mt-4
    = f.fields_for :project_customers do |project_customer|
      = render 'project_customer_fields', f: project_customer
    .links
      = link_to_add_association '顧客追加', f, :project_customers, class: 'btn btn-primary'
    .customer-link.mt-4.mb-4
      = link_to '顧客一覧へ', customers_path, target: "_blank", class: 'btn btn-primary'
  .form-group.row
    .col-sm-6
      = f.label :application_date, '申請日'
      = f.date_field :application_date, class: 'form-control'
    .col-sm-6
      = f.label :complete_date, '完了日'
      = f.date_field :complete_date, class: 'form-control'
  #certificates.mb-4
    = f.fields_for :certificates do |certificate|
      = render 'certificate_fields', f: certificate
    .links
      = link_to_add_association '謄本追加', f, :certificates, class: 'btn btn-primary'
  .form-group
    = f.label :remarks, '備考'
    = f.text_area :remarks, class: 'form-control'

  #destinates.mb-4
    = f.fields_for :destinates do |destinate|
      = render 'destinate_fields', f: destinate
    .links
      = link_to_add_association '書類送付追加', f, :destinates, class: 'btn btn-primary'

  .form-group
    = f.label :image
    = f.file_field :images, multipre: true, class: 'form-control'

  .form-group
    p = '現在登録されているファイル（削除するものはチェックしてください）'
    - newbuild.images.each do |image|
      = f.check_box :image_ids, {:multiple => true, class: 'form-check-label'}, image.id, false
      span.mr-3 =  image.filename
  = f.submit '登録する', class: 'btn btn-primary m-3'


app/views/newbuilds/_project_customer_fields.html.slim
.nested-fields.well.well-compact
  .form-group.mb-2
    = f.hidden_field :id 

    = f.label :customer_id, '顧客氏名'
    = f.collection_select(:customer_id, f.object.selectable_customers, :id, :view_name_select, {include_blank: true, prompt: "選択してください"}, class: 'form-control select2')
    .row.mt-4.mb-4
      .col-sm-1.text-right.mb-4
        = f.label :equity, "持分"
      .col-sm-2
        = f.text_field :equity, class: 'form-control'

      .col-sm-3.text-right
        = f.label :position, '顧客・事業主等'
      .col-sm-4
        = f.select :position, ProjectCustomer.new_position_select, {prompt: true, include_blank: true}, {class: 'form-control'}
      
      .col-sm-4
        = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/newbuilds/_project_estate_fields.html.slim
.nested-fields.well.well-compact
  .form-group.mb-2.row
    = f.hidden_field :id 
    .col-sm-1
      = f.label :estate_id, '不動産'
    .col-sm-10
      = f.collection_select(:estate_id, Estate.all, :id, :view_estate_select, {include_blank: true, prompt: "選択してください"}, class: 'form-control select2')
    .col-sm-1
      = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/newbuilds/edit.html.slim
- @page_title = '新築案件編集'
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '案件詳細へ', newbuild_path, class: 'nav-link btn btn-primary'
  = link_to '新築案件一覧へ', newbuilds_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '案件一覧へ', projects_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'

= render 'form', newbuild: @newbuild

app/views/newbuilds/index.html.slim
- @page_title = "新築案件一覧"
h3.mb-3.mt-3 = @page_title

nav.navbar.navbar-expand-md.navbar-dark.bg-primary 
  ul.navbar-nav.mr-auto
    li.nav-item = link_to '案件一覧', projects_path, class: 'nav-link text-white'
    li.nav-item = link_to '新築案件新規作成', new_newbuild_path, class: 'nav-link  text-white'
    li.nav-item = link_to '事件簿TOP', casefiles_path, class: 'nav-link  text-white'

button#search-btn.btn-warning.m-2= "検索表示"
fieldset#search.border.mb-3.d-none
  legend.pl-3 検索
  .pl-1
    = render 'shared/project_search'
.mb-3
  = paginate @newbuilds
  = page_entries_info @newbuilds

.mb-3
table.table.table-hover.table-bordered.text-center
  thead.table-default
    tr
      th = Common.human_attribute_name(:id).upcase
      th = Common.human_attribute_name(:name)
      th = Common.human_attribute_name(:application_date)
      th = Common.human_attribute_name(:status)
      th = Common.human_attribute_name(:user)
      th
  tbody
    - @newbuilds.each do |newbuild|
      tr
        td = newbuild.id
        td = link_to newbuild.name, newbuild
        td = newbuild.application_date.try(:strftime, '%Y/%m/%d-%H:%M')
        td = newbuild.status
        td = newbuild.user.name
        td
          = link_to '編集', [:edit, newbuild], class: 'btn btn-primary m-1'
          - if current_user.admin?
            = link_to '削除', newbuild, method: :delete, data: { confirm: "#{newbuild.name}を削除します。よろしいですか？"}, class: 'btn btn-danger m-1'

app/views/newbuilds/new.html.slim
- @page_title = "新築案件新規作成"
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '新築案件一覧へ', newbuilds_path, class: 'nav-link btn btn-primary'
  = link_to '案件一覧へ', projects_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'

= render 'form', newbuild: @newbuild

app/views/newbuilds/show.html.slim
- @page_title = "新築案件詳細（更新日：#{@newbuild.updated_at.try(:strftime, "%Y/%m/%d")})"
.pb-2.d-print-none
  .row.mb-2
    | 事件簿
  .row.mb-2
    - if @newbuild.casefiles.blank?
      .col-sm-12.bg-danger.text-white
        = "事件簿を入力してください！！"
    - else
      - @newbuild.casefiles.each do |casefile|
        .col-sm-3
          = link_to casefile.event_title, casefile
  .row.mb-2
    | 当事者一覧リンク
  .row.mb-2
    - @newbuild.project_customers.each do |customer|
      = link_to "「#{customer.position}：#{customer.customer.name}」", customer.customer
  .row.mb-2
    | 登録ファイル
  .row.mb-2
    - if @newbuild.images.attached?
      - @newbuild.images.each do |image|
          span.mr-5
            = link_to image.filename, image,:target => "_blank" 
  .row.mb-2
    | 登記照会
  .row.mb-2
    - if @newbuild.judges.present?
      - @newbuild.judges.each do |judge|
        = link_to judge.title, judge
  h3.mb-3.mt-3.d-print-none 
    = @page_title
  
  .nav.justify-content-end.m-3.d-print-none
    = link_to '編集', edit_newbuild_path, class: 'btn btn-primary mb-3'
    - if current_user.admin?
      = link_to '削除', :newbuild, method: :delete, data: {confirm: "#{@newbuild.name}を削除してよろしいですか？" }, class: 'btn btn-danger mb-3 ml-3'
    = link_to '経費登録', new_project_cost_path(@newbuild), class: 'nav-link btn btn-primary mb-3 ml-3'
    = link_to '経費明細', project_costs_path(@newbuild), class: 'nav-link btn btn-primary mb-3 ml-3'
    = link_to '新築案件一覧', newbuilds_path, class: 'nav-link btn btn-primary mb-3 ml-3'
    = link_to '案件一覧', projects_path, class: 'nav-link btn btn-primary mb-3 ml-3'
    = link_to '事件簿ＴＯＰ', casefiles_path, class: 'nav-link btn btn-primary mb-3 ml-3'
    = link_to '戻る', :back, class: 'nav-link btn btn-primary mb-3 ml-3'

.text-align-center.m-2 style="font-size: 1.1rem;"
  .row
    .col-sm-1.p-2.border.border-dark
      | ID：
      = @newbuild.id
    .col-sm-5.p-2.border-top.border-right.border-bottom.border-dark
      |　案件名：
      = @newbuild.name
    .col-sm-4.p-2.border-top.border-bottom.border-dark
      | 進捗状況：
      = @newbuild.status
    .col-sm-2.p-2.border.border-dark
      | 事務所担当: 
      = @newbuild.user.name

  .row.border-right.border-left.border-dark
    .col-sm-2.p-3
      | 不動産の表示
    .col-sm-10.p-2
      .row
        - @newbuild.project_estates.each do |estate|
          .col-sm-8.p-1
            = link_to "#{estate.estate.view_estate_select}", estate.estate
          .col-sm-4.p-1
            = "管轄：#{ProjectEstate.control_name(estate)}"
          br

  .row.border.border-dark
    .col-sm-2.p-3
      | 事業主
    .col-sm-4.p-3
      - ProjectCustomer.customer_select(@newbuild, "事業主").each do |customer|
        - if customer.present?
          = customer[:name]
          br
    .col-sm-3.p-3
      - ProjectCustomer.branch_select(@newbuild, "事業主担当者").each do |branch|
        - if branch.present?
        = branch.branch.branch_name

    .col-sm-3.p-3
      - ProjectCustomer.customer_select(@newbuild, "事業主担当者").each do |customer|
        | 担当者：  
        -if customer.present?
          = customer[:name]
          br
  .row.border-left.border-right.border-bottom.border-dark
    .col-sm-2.p-3
      | 販売
    .col-sm-4.p-3
      - ProjectCustomer.customer_select(@newbuild, "販売代理").each do |customer|
        - if customer.present?
          = customer[:name]
          br
    .col-sm-3.p-3
      - ProjectCustomer.branch_select(@newbuild, "販売担当者").each do |branch|
        - if branch.present?
          = branch.branch.branch_name

    .col-sm-3.p-3
      - ProjectCustomer.customer_select(@newbuild, "販売担当者").each do |customer|
        | 担当者：  
        -if customer.present?
          = customer[:name]
          br
  .row
    .col-sm-2.p-3.border-left.border-dark
      | 融資先
    .col-sm-4.p-3.border-dark
      - ProjectCustomer.customer_select(@newbuild, "融資先").each do |customer|
        = customer[:name]
        br
    .col-sm-3.p-3.border-dark
      - ProjectCustomer.branch_select(@newbuild, "融資先担当者").each do |branch|
        - if branch.present?
          = branch.branch.branch_name
          = branch.title
          br
    .col-sm-3.p-3.border-right.border-dark
      | 担当者：
      - ProjectCustomer.customer_select(@newbuild, "融資先担当者").each do |customer|
        = customer[:name]
        br
  .row
    .col-sm-2.p-3.border-left.border-top.border-dark
      | 司法書士：
    .col-sm-10.p-3.border-top.border-right.border-dark
      - ProjectCustomer.customer_select(@newbuild, "司法書士").each do |customer|
        = customer[:name]
        br
  .row
    .col-sm-2.p-3.border-left.border-top.border-dark
      | 調査士：
    .col-sm-10.p-3.border-top.border-right.border-dark
      - ProjectCustomer.customer_select(@newbuild, "土地家屋調査士").each do |customer|
        = customer[:name]
        br
  .row.border-left.border-right.border-top.border-dark style="height: 200px;"
    .col-sm-2.p-3
      | 依頼内容：
    .col-sm-10.p-3
      = simple_format(@newbuild.request_content)
  
  .row.border-left.border-right.border-top.border-dark
    .col-sm-2.p-2
      | 備考：
    .col-sm-10.p-2
      = simple_format(@newbuild.remarks)
  
  .row.border.border-dark
    .col-sm-1.p-1
      | 申請日：
    .col-sm-2.p-1
      = @newbuild.application_date.try(:strftime, "%Y/%m/%d(%a)")
    .col-sm-1.p-1
      | 補正日：
    .col-sm-2.p-1
      = @newbuild.complete_date.try(:strftime, "%Y/%m/%d(%a)")
    .col-sm-1.p-1
      | 謄本：
    .col-sm-3.p-1
      - @newbuild.certificates.each do |cert|
        = cert.cert_kind
        = " #{cert.number_sheet} 通　"
        = cert.window? ? "窓口受取" : "オンライン"
        br
  .row.p-2.border-left.border-right.border-bottom.border-dark
    | 完了書類送付
  - if @newbuild.destinates.present?

    - @newbuild.destinates.each do |destinate|
      .row
        .col-sm-6.p-2.border-left.border-dark
          | 氏名：　
          = destinate.customer.name
        .col-sm-6.p-2.border-right.border-dark
          | 送付先等：　
          = destinate.send_addr
      .row
        .col-sm-3.p-2.border-left.border-bottom.border-dark
          | 送付日：
          = destinate.send_date.try(:strftime, "%Y/%m/%d(%a)")
        .col-sm-1.p-2.border-bottom.border-dark
          = destinate.send_method? ? "手渡" : "送付"
        .col-sm-4.p-2.border-bottom.border-dark
          | 書留等番号：　
          = link_to destinate.send_number, "https://trackings.post.japanpost.jp/services/srv/search/?requestNo1=#{destinate.send_number}&search.x=74&search.y=14&startingUrlPatten=&locale=ja", target: :_blank if destinate.send_number != nil
        .col-sm-4.p-2.border-bottom.border-right.border-dark
          | 受領書返送：　
          = destinate.receive_doc? ? "済" : "未"
  - else
    
  . style="page-break-before: always;"
  = "本人確認記録"  
    
= render 'shared/title_back', newbuild: @newbuild 
  