config/routes.rb
Rails.application.routes.draw do
  
  get 'customers', to: 'customers#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :account, only: [:show, :edit, :update]

  resources :casefiles do
    post :import, on: :collection
    get :get_report, on: :collection
  end
  resources :projects do 
    resources :costs
  end
  resources :rehouses
  resources :landfs
  resources :inherits
  resources :genes
  resources :commons
  resources :corps
  resources :newbuilds
  resources :mitsuwa_docs
  resources :mistakes
  resources :judges

  resources :estates, only: :index
  resources :lands do
    post :import, on: :collection
  end
  resources :buildings do
    post :import, on: :collection
  end
  resources :aparts do
    post :import, on: :collection
  end
  resources :rooms do
    post :import, on: :collection
  end

  resources :gifts
  resources :addresses
  resources :tels
  resources :mails
  resources :costs
  resources :customer_agents
  resources :branch_staffs
  resources :identifies
  resources :branches do
    resources :branch_staffs
  end

  resources :controls do
    resources :addresses do
      get :addaddr, on: :collection
    end
    resource :tels do
      get :addcontrol, on: :collection
    end
    resources :mails do
      get :addcontrol, on: :collection
    end
    post :import, on: :collection
  end

  resources :people do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    post :import, on: :collection
  end

  resources :companies do
    resources :addresses
    resources :identifies
    resources :branches
    resources :tels
    resources :mails
    post :import, on: :collection
  end

  resources :agents do
    resources :addresses
  end

  resources :customers do
    resources :addresses
    resources :tels
    resources :mails
    resources :identifies
    resources :gifts
    resources :customer_agents
  end

  namespace :admin do
    resources :users
  end

  # ---------------------------------
  # 仮のルートページ
  # ---------------------------------
  root 'customers#index'
end

app/models/company.rb
class Company < Customer
  has_many :customer_agents, foreign_key: :customer_id
  has_many :agents, class_name: 'Customer', through: :customer_agents
  accepts_nested_attributes_for :customer_agents, allow_destroy: true
  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses
  has_many :identifies, foreign_key: :customer_id, dependent: :destroy
  has_many :branches, foreign_key: :customer_id

  has_many :company_controls, foreign_key: :company_id, inverse_of: :company, dependent: :destroy
  has_many :controls, through: :company_controls, source: :control
  accepts_nested_attributes_for :company_controls,  reject_if: :all_blank, allow_destroy: true

  has_many :tels, as: :telable, dependent: :destroy
  accepts_nested_attributes_for :tels
  has_many :mails, as: :mailable, dependent: :destroy
  accepts_nested_attributes_for :mails

  # 設立年月日validateに定義したメソッドを設定
  validate :establishment_cannot_be_in_the_future
  # 次回申請期日validateに定義したメソッドを設定
  validate :next_application_cannot_be_in_the_future
  # 会社法人等番号は12桁　ハイフン無　数字のみ
  validates :company_number, numericality: :only_integr, length: { is: 12, message: 'は12桁の数字（ハイフン無）で入力してください。' }, allow_blank: true
  # 決算期は　1~12のみ
  validates :fiscal_year, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 12, message: '１～１２の範囲で指定してください' }, allow_blank: true

  def self.csv_attributes
    %w(id name kana establishment company_number fiscal_year next_application type created_at updated_at)
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |company|
        csv << csv_attributes.map { |attr| company.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      company = new
      company.attributes = row.to_hash.slice(*csv_attributes)
      company.save!
    end
  end

  private

  # 設立年月日の未来日のチェックメソッド
  def establishment_cannot_be_in_the_future
    # 設立年月日が入力済かつ未来日(現在日付より未来)
    if establishment.present? && establishment > Date.today
      # エラー対象とするプロパティ(establishment)とエラーメッセージを設定
      errors.add(:establishment, "は過去の日付を指定してください")
    end
  end

  # 次回申請期日の過去日のチェックメソッド
  def next_application_cannot_be_in_the_future
    # 設立年月日が入力済かつ未来日(現在日付より未来)
    if next_application.present? && next_application < Date.today
      # エラー対象とするプロパティ(establishment)とエラーメッセージを設定
      errors.add(:next_application, "は未来の日付を指定してください")
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result.page(params[:page]).per(10)
    @companys = @q.result(distinct: true)

    respond_to do |format|
      format.html
      format.csv { send_data @companys.generate_csv, filename: "companies-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def show
    @agents = CustomerAgent.where(agent_id: params[:id]).order('updated_at desc')
  end

  def new
    @company = Company.new
    @company.addresses.build
    @company.company_controls.build
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.addresses.build(address_params)

    if @company.save
      redirect_to company_path(@company), notice: "#{@company.name}を登録しました。"
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to company_path(@company), notice: "#{@company.name}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_path, notice: "#{@company.name}を削除しました。"
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: '法人顧客をファイルから追加しました。'
  end

  private

  def company_params
    params.require(:company).permit(:name, :kana, :type, :establishment, :company_number, :fiscal_year, :next_application, tels_attributes: [:id, :tel_kind, :tel_number, :_destroy], mails_attributes: [:id, :mail_kind, :mail_address, :_destroy], company_controls_attributes: [:id, :company_id, :control_id, :control_kind, :_destroy])
  end

  def address_params
    params.require(:address).permit(:zip, :address, :since_date, :address_kind, :address_closure)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company_control_fields.html.slim
.nested-fields.well.well-compact
  .form-group.mb-2
    = f.hidden_field :id 

    = f.label :control_id, '管轄法務局'
    = f.collection_select(:control_id, Control.all, :id, :name, {include_blank: true, prompt: "選択してください"}, class: 'form-control select2')
    .row.mt-4
      .col-sm-3.mb-2.text-right
        = f.label :control_kind, '本店・支店・本店移転先等'
      .col-sm-4
        = f.select :control_kind, ['本店管轄','支店管轄'], {include_blank: true, prompt: "選択してください"}, class: 'form-control'
      .col-sm-4
        = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/companies/_edit_form.html.slim
- if company.errors.present?
  ul#error_explanation
    - company.errors.full_messages.each do |message|
      li = message
= form_with model: company, local: true do |f|
  .form-group
    = f.label :name, '商号'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :kana, 'フリガナ'
    = f.text_field :kana, class: 'form-control'
  #company_controls.mb-4.mt-4
    = f.fields_for :company_controls do |company_control|
      = render 'company_control_fields', f: company_control
    .links
      = link_to_add_association '管轄追加', f, :company_controls, class: 'btn btn-primary'
    .estate-link.mt-4.mb-4
  .form-group
    = f.label :establishment, '設立年月日'
    = f.date_field :establishment, class: 'form-control'
  .form-group
    = f.label :company_number, '会社法人等番号'
    = f.text_field :company_number, class: 'form-control'
  .form-group
    = f.label :fiscal_year, '決算月'
    = f.number_field :fiscal_year, class: 'form-control'
  .form-group
    = f.label :next_application, '次回申請期日'
    = f.date_field :next_application, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'
    
  

app/views/companies/_form.html.slim
- if company.errors.present?
  ul#error_explanation
    - company.errors.full_messages.each do |message|
      li = message
= form_with model: company, local: true do |f|
  .form-group
    = f.label :name, '商号'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :kana, 'フリガナ'
    = f.text_field :kana, class: 'form-control'
  .form-group
    = fields_for :address do |a|
      = label :zip, '郵便番号'
      = a.text_field :zip, class: 'form-control'
      = a.label :address, '本店'
      = a.text_field :address, class: 'form-control'
      = a.label :since_date, '本店を置いた日'
      = a.date_field :since_date, class: 'form-control'
      = a.label :address_kind, '本店の種類'
      = a.text_field :address_kind, class: 'form-control'
      = a.hidden_field :address_closure, value: false, class: 'form-control'
  #company_controls.mb-4.mt-4
    = f.fields_for :company_controls do |company_control|
      = render 'company_control_fields', f: company_control
    .links
      = link_to_add_association '管轄追加', f, :company_controls, class: 'btn btn-primary'
    .estate-link.mt-4.mb-4
  .form-group
    = f.label :establishment, '設立年月日'
    = f.date_field :establishment, class: 'form-control'
  .form-group
    = f.label :company_number, '会社法人等番号'
    = f.text_field :company_number, class: 'form-control'
  #tels.mb-2
    = f.fields_for :tels do |tel|
      = render 'tel_fields', f: tel
    .links
      = link_to_add_association '電話番号追加', f, :tels, class: 'btn btn-primary'
  #mails.mb-2
    = f.fields_for :mails do |tel|
      = render 'mail_fields', f: tel
    .links
      = link_to_add_association 'メールアドレス追加', f, :mails, class: 'btn btn-primary'
  .form-group
    = f.label :fiscal_year, '決算月'
    = f.number_field :fiscal_year, class: 'form-control'
  .form-group
    = f.label :next_application, '次回申請期日'
    = f.date_field :next_application, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'
    
  

app/views/companies/_mail_fields.html.slim
.nested-fields.well.well-compact
  .form-group
    = f.hidden_field :id
    .row
      .col-sm-3
        = f.label :mail_kind, 'メール種類'
        = f.text_field :mail_kind, class: 'form-control'
      .col-sm-6
        = f.label :mail_address, 'メールアドレス'
        = f.text_field :mail_address, class:  'form-control'
      .col-sm-3
        = link_to_remove_association '削除', f, class: 'btn btn-danger mt-4'

app/views/companies/_tel_fields.html.slim
.nested-fields.well.well-compact
  .form-group
    = f.hidden_field :id
    .row
      .col-sm-3
        = f.label :tel_kind, '電話種類'
        = f.text_field :tel_kind, class: 'form-control'
      .col-sm-6
        = f.label :tel_number, '電話番号'
        = f.text_field :tel_number, class:  'form-control'
      .col-sm-3
        = link_to_remove_association '削除', f, class: 'btn btn-danger mt-4'

app/views/companies/edit.html.slim
- @page_title = '法人顧客編集'
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '顧客詳細へ', company_path, class: 'nav-link btn btn-primary'
  = link_to '法人顧客一覧へ', companies_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '顧客一覧へ', customers_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'

= render 'edit_form', company: @company

app/views/companies/index.html.slim
- @page_title = "法人顧客"
h3.mb-3.mt-3 = @page_title

nav.navbar.navbar-expand-md.navbar-dark.bg-primary 
  ul.navbar-nav.mr-auto
    li.nav-item = link_to '法人顧客新規作成', new_company_path, class: 'nav-link text-white'
    li.nav-item = link_to '個人顧客一覧', people_path, class: 'nav-link text-white'
    li.nav-item = link_to '代理人・代表者関連作成', new_customer_agent_path, class: 'nav-link text-white'
    li.nav-item = link_to '顧客一覧', customers_path, class: 'nav-link text-white'

button#search-btn.btn-warning.m-2= "検索表示"
fieldset#search.border.mb-3.d-none
  legend.pl-3 検索
  .pl-1
    = render 'shared/search'

.mb-3
  = paginate @companies
  = page_entries_info @companies

.mb-3
table.table.table-hover.table-bordered.text-center
  thead.table-dafault
    tr
      th = Company.human_attribute_name(:id).upcase
      th = Company.human_attribute_name(:name)
      th = sort_link(@q, :kana)
      th = Company.human_attribute_name(:company_number)
      th = Company.human_attribute_name(:next_application)
      th = Company.human_attribute_name(:created_at)
      th = Company.human_attribute_name(:updated_at)
      th
  tbody
    - @companies.each do |company|
      tr
        td = company.id
        td = link_to company.name, company_path(company)
        td = company.kana
        td = company.company_number
        td = company.next_application.try(:strftime,'%Y/%m/%d')
        td = company.created_at.try(:strftime,'%Y/%m/%d')
        td = company.updated_at.try(:strftime,'%Y/%m/%d')
        td
          = link_to '編集', edit_company_path(company), class: 'btn btn-primary mr-3'
          - if current_user.admin?
            = link_to '削除', company, method: :delete, data: { confirm: "#{company.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'

= link_to 'エクスポート', companies_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_companies_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag 'インポート', class: 'btn btn-primary'

app/views/companies/new.html.slim
- @page_title = "法人顧客新規作成"
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '法人顧客一覧へ', companies_path, class: 'nav-link btn btn-primary'
  = link_to '顧客一覧へ', customers_path, class: 'nav-link btn btn-primary ml-3'
  = link_to '戻る', :back, class: 'nav-link btn btn-primary ml-3'
  

= render 'form', company: @company

app/views/companies/show.html.slim
- @page_title = "法人顧客詳細"
h3.mb-3.mt-3 = @page_title

.nav.justify-content-end
  = link_to '編集', edit_company_path, class: 'btn btn-primary mb-3'
  - if current_user.admin?
    = link_to '削除', :company, method: :delete, data: {confirm: "#{@company.name}を削除してよろしいですか？" }, class: 'btn btn-danger mb-3 ml-3'
  = link_to '本人確認記録作成', new_customer_identify_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '本店追加', new_customer_address_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '本支店追加', new_company_branch_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '電話追加', new_customer_tel_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to 'メール追加', new_customer_mail_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '代表者等作成', new_customer_customer_agent_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '贈答品登録', new_customer_gift_path(@company), class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '法人一覧', companies_path, class: 'nav-link btn btn-primary mb-3 ml-3'
  = link_to '顧客一覧', customers_path, class: 'nav-link btn btn-primary mb-3 ml-3'

table.table.table-hover.table-bordered
  tbody
    tr
      th.w-25 = Company.human_attribute_name(:id).upcase
      td = @company.id
    tr
      th = Company.human_attribute_name(:name)
      td = @company.name
    tr
      th = Company.human_attribute_name(:kana)
      td = @company.kana
    tr
      th = Company.human_attribute_name(:address)
      td
        - if @company.addresses.present?
          - @company.addresses.order('since_date desc').each do |a|
            - if a.address_closure == false
              .row
                .col-sm-6
                  = "本店を置いた日： #{a.since_date.try(:strftime, '%Y/%m/%d')}"
                .col-sm-5
                  |　住所の種類:　
                  = a.address_kind
              .row.mb-2
                .col-sm-2
                  = "〒#{a.zip}" 
                .col-sm-7
                  = a.address
                .col-sm-1
                  = link_to "編集", [:edit, @customer, a], class: 'btn btn-primary pull-right'
                .col-sm-1
                  = link_to "削除", [@customer, a], method: :delete, data: {confirm: "#{a.address}を削除します。よろしいですか？"} ,class: 'btn btn-danger pull-right'
    tr
      th = Company.human_attribute_name(:control)
      td 
        - @company.company_controls.each do |control|
          = "#{control.control_kind}：　 #{control.control.name}"
          br

    tr
      th = Company.human_attribute_name(:establishment)
      td = @company.establishment.try(:strftime,'%Y/%m/%d')
    tr
      th = Company.human_attribute_name(:company_number)
      td = @company.company_number
    tr      
      th = Company.human_attribute_name(:agent)
      td.justify-content-end
        - @company.customer_agents.order("updated_at desc").each do |agent|
          .row
            .col-sm-4.text-right
              = link_to agent.customer.name, agent.customer
              |の
              = agent.title
            .col-sm-4
              = link_to agent.agent.name, agent.agent
            .col-sm-1
              = link_to "編集", [:edit, @customer, agent], class: 'btn btn-primary pull-right'
            .col-sm-1
              = link_to "削除", agent, method: :delete, data: {confirm: "#{agent.customer.name}の代理人を削除しますよろしいですか？"}, class: 'btn btn-danger'
          .row.mb-2
            .col-sm-4.text-right
              = Company.human_attribute_name(:updated_at)
            .col-sm-6
              = agent.updated_at.try(:strftime,' %Y/%m/%d-%H:%M')
    tr
      th = Company.human_attribute_name(:tel)
      td
        - @company.tels.each do |tel|
          .row.mb-2
            .col-sm-3
              = tel.tel_kind
            .col-sm-3
              = tel.tel_number
            .col-sm-1
              = link_to "編集", [:edit, @customer, tel], class: 'btn btn-primary pull-right'
            .col-sm-1
              = link_to "削除", [@customer, tel], method: :delete, data: {confirm: "#{tel.tel_number}を削除します。よろしいですか？"} ,class: 'btn btn-danger pull-right'
    tr
      th = Company.human_attribute_name(:mail)
      td
        - @company.mails.each do |mail|
          .row.mb-2
            .col-sm-3
              = mail.mail_kind
            .col-sm-3
              = mail_to mail.mail_address
            .col-sm-1
              = link_to "編集", [:edit, @customer, mail], class: 'btn btn-primary pull-right'
            .col-sm-1
              = link_to "削除", [@customer, mail], method: :delete, data: {confirm: "#{mail.mail_address}を削除します。よろしいですか？"} ,class: 'btn btn-danger pull-right'
    tr
      th = Company.human_attribute_name(:agent_customer)
      td
        - @agents.each do |customer|
          .row
            .col-sm-6
              = link_to customer.customer.name, customer.customer
              |の
              = customer.title
            .col-sm-2
              = Company.human_attribute_name(:updated_at)
            .col-sm-4
              = customer.updated_at.try(:strftime,' %Y/%m/%d-%H:%M')
    tr
      th = Company.human_attribute_name(:identify)
      td
        - @company.identifies.each do |identify|
          .row
            .col-sm-2
              = identify.ident_method
              |:
            .col-sm-2
              = link_to identify.date_time.try(:strftime, "%Y/%m/%d"), identify
            .col-sm-2
              |確認者：
              = identify.user.name
    tr
      th = Company.human_attribute_name(:branch)
      td
        - @company.branches.each do |branch|
          .row.mb-2
            .col-sm-8
              = link_to branch.branch_name, branch
            .col-sm-1
              = link_to "編集", [:edit, @company, branch], class: 'btn btn-primary pull-right'
            .col-sm-1
              = link_to "削除", branch, method: :delete, data: {confirm: "#{branch.branch_name}を削除しますよろしいですか？"}, class: 'btn btn-danger'

    tr
      th = Company.human_attribute_name(:fiscal_year)
      td 
        = @company.fiscal_year 
        | 月
    tr
      th = Company.human_attribute_name(:gift)
      td
        - @company.gifts.each do |gift|
          .row.m-2
            .col-sm-3
              = link_to "#{gift.gift_year}年：", gift
              = gift.gift_kind
              = gift.send_receive
            .col-sm-2
              = gift.gift_address
            .col-sm-2
              = gift.gift_remark.truncate(8)
            .col-sm-1
              = link_to "編集", [:edit, gift], class: 'btn btn-primary'
            .col-sm-1
              = link_to "削除", gift, method: :delete, data: {confirm: "#{gift.gift_year}年#{gift.gift_kind}を削除しますよろしいですか？"}, class: 'btn btn-danger'
    tr
      th = Company.human_attribute_name(:next_application)
      td = @company.next_application.try(:strftime,'%Y/%m/%d')
    tr
      th = Company.human_attribute_name(:old_address)
      td
        - if @company.addresses.present?
          - @company.addresses.order('since_date desc').each do |a|
            - if a.address_closure == true
              card.row              
                .col-sm-6
                  = "本店を置いた日：  #{a.since_date.try(:strftime,'%Y/%m/%d')}"
                .col-sm-5
                  |　住所の種類：
                  = a.address_kind
              .row.mb-2
                .col-sm-2
                  = "〒#{a.zip}"
                .col-sm-7
                  = a.address
                .col-sm-1
                  = link_to "編集", [:edit, @customer, a], class: 'btn btn-primary pull-right'
                .col-sm-1
                  = link_to "削除", [@customer, a], method: :delete, data: {confirm: "#{a.address}を削除します。よろしいですか？"} ,class: 'btn btn-danger pull-right'
    tr
      th = Company.human_attribute_name(:created_at)
      td = @company.created_at.try(:strftime,'%Y/%m/%d')
    tr
      th = Company.human_attribute_name(:updated_at)
      td = @company.updated_at.try(:strftime,'%Y/%m/%d')